# Generated by Django 6.0 on 2025-12-22 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0002_friend_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('msg_reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_reciever', to='mychatapp.profile')),
                ('msg_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to='mychatapp.profile')),
            ],
        ),
    ]
